package gitlet;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Created with IntelliJ IDEA.
 * Copyright@:
 *
 * @Author: Pan Zifeng
 * @Date: 2021/06/12/22:38
 * @Description: used to describe the file commited.
 */
public class Blob implements Serializable {

    // create time
    private final String _Time;
    // the origin file name(not the name used the SHA-1)
    private final String _BlobName;
    // the ID is generated by the hash function.
    private String _BlobID;
    // stores the content of one file
    private final String _Content;

    private boolean removeFlag = false;
    private boolean modifiedFlag = false;


    public Blob(String _BlobName, String _Content) {
        this._Time = DateTimeFormatter.ISO_DATE_TIME.format(LocalDateTime.now());
        this._BlobName = _BlobName;
        this._Content = _Content;
    }

    public String get_Time() {
        return _Time;
    }

    public String get_BlobName() {
        return _BlobName;
    }

    public String get_BlobID() {
        return _BlobID;
    }

    public String get_Content() {
        return _Content;
    }

    public void set_BlobID(String _BlobID) {
        this._BlobID = _BlobID;
    }

    public void setRemoveFlag(boolean removeFlag) {
        this.removeFlag = removeFlag;
    }

    public void setModifiedFlag(boolean modifiedFlag) {
        this.modifiedFlag = modifiedFlag;
    }
}
